matrix:
  include:
    - language: python
      python: 3.8
      before_script:
        - cd ./SeniorSidekick/backend/Sunshine/
      install:
        - pip install -r ./SeniorSidekick/backend/Sunshine/requirements.txt
      addons:
        postgresql: "12"
        apt:
          packages:
          - postgresql-12
          - postgresql-client-12
      env:
        global:
        - PGUSER=postgres
        - PGPORT=5432
      script:
        - python manage.py test
        
    - language: node_js
      node_js: "10"
      before_script:
        - cd ./SeniorSidekick/frontend/
      install:
        - npm install
      script:
        - npm test
